### ISSUE TITLE
[wine] Steam "Dark Souls: Prepare to Die Edition [-dsptde-2.0-]" black window content

### ISSUE THREAD

**Issue by karolherbst** [amonakov/primus#156]
it seems to react to mouse events though and it kind of works with optirun, allthough the performance seems bad.

**Comment by karolherbst** [comment]
also it crashes (or quits) when the game tries to go into fullscreen mode (it starts in window mode first)

**Comment by karolherbst** [comment]
and sometimes the game hangs with "primus: fatal: failed to acquire direct rendering context for display thread" at start.

**Comment by ArchangeGabriel** [comment]
Is this with primus git, or before end december updates? I had a game (Relics of Annorath) crashing before, but with latest updates it works.

**Comment by karolherbst** [comment]
I am usually on recent master.

**Comment by karolherbst** [comment]
I think the same issue exists in GTA IV when starting the performance benchmark. Don't know if there are related, but GTA has a context switch and primus failes to aquire a direct rendering context :/

**Comment by amonakov** [comment]
As in previous bugs, I have to ask for apitrace traces to look at the problem. You know the drill :)

**Comment by karolherbst** [comment]
yeah I already thought that much :/ I think I may be able to do it tomorrow.

**Comment by amonakov** [comment]
Since #159 was similar and is now fixed, there's a chance that the fix for #160 also fixes some of the problems here.

**Comment by karolherbst** [comment]
yeah, this is fixed.
