### ISSUE TITLE
SuperTuxKart segfaults with primus when applying new graphics settings

### ISSUE THREAD

**Issue by akien-mga** [amonakov/primus#160]
I've tested SuperTuxKart 0.8.1, 0.8.2-beta and 0.8.2-beta2 (released today), all three versions crash when you try to reconfigure the graphics settings (it recreates the whole GL context AFAIU).

The crash only happens when using primus, there is no issue with VirtualGL (and no issue with my Intel GPU and mesa either).

I'm using the 346.35 version of nvidia's drivers, with the latest master branch for primus.

I'd gladly provide a backtrace, but I'm a gdb noob and I can't manage to get a backtrace for "optirun -b primus supertuxkart" (obviously ```gdb optirun -b primus supertuxkart``` does not work).

**Comment by akien-mga** [comment]
I tested both a locally built STK 0.8.2-beta2 and the upstream portable Linux package, both present the issue.

**Comment by amonakov** [comment]
`optirun -b primus gdb supertuxkart` and in gdb `thread apply all bt`; thanks

**Comment by akien-mga** [comment]
Here's the output: https://bpaste.net/show/072edc1400d0

**Comment by amonakov** [comment]
Thanks for the report; I've pushed a patch that should fix the issue, please report if problems remain.

**Comment by akien-mga** [comment]
Thanks for the quick fix! I tested the patch and it does fix the issue :-)
