### ISSUE TITLE
Xcom enemy within crashes on exit with primus

### ISSUE THREAD

**Issue by leander091** [amonakov/primus#161]
Hello, 
When i exit the game. It crashes.  
Im using Archlinux with a Nvidia 760M  and a Intel HD Graphics 4600

I have attached the console output.
Could you help me?
https://gist.github.com/leander091/18c1e301191d53f54d4e

**Comment by amonakov** [comment]
The console output doesn't indicate a problem with primus. Also, at the moment Arch Linux packages are one commit behind. Can you please check with git version?

**Comment by leander091** [comment]
Thank you for the suggestion. I've recompiled the latest version and there are no crashes anymore.
