### ISSUE TITLE
32 bit apps now requiring PRIMUS_UPLOAD=1

### ISSUE THREAD

**Issue by WhiteWolf1776** [amonakov/primus#167]
After a huge batch of updates in slackware's testing branch, I've hit an issue I'm unable to work out.  Any ideas you guys may have I would seriously appreciate.

First, 64bit native apps run just fine with primus, but x86 apps via multilib... just fail to a black screen.

Error Output:
X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  72 (X_PutImage)
  Serial number of failed request:  42
  Current serial number in output stream:  81

primus: warning: dropping a frame to avoid deadlock
primus: warning: timeout waiting for display worker
signal caught: Segmentation fault

With PRIMUS_UPLOAD=1, 32 bit apps run ok.  Seems a little slower on the framerate to me, but I haven't yet gotten a benchmark on it.

**Comment by amonakov** [comment]
Does it happen with PRIMUS_UPLOAD=2? Can you run glsanity to make sure libs are in order?

**Comment by WhiteWolf1776** [comment]
PRIMUS_UPLOAD=2 also works for 32 bit apps, may just be me but seems better frame rates than PRIMUS_UPLOAD=1.

glsanity output:

Checking native (usually Mesa/i965) GL
Running 32-bit tests
info:  libGL.so.1:      loaded from: /usr/lib/libGL.so.1
info:  libGL.so.1:      symlink to:  /usr/lib/libGL.so.1.2.0
info:  X display:       :0
info:  X Ext. "GLX":    present
info:  X Ext. "NV-GLX": not present; OK for non-nVidia drivers
libGL error: unable to load driver: i965_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: i965
info:  GLX server:      SGI
info:  GLX client:      Mesa Project and SGI
info:  GL vendor:       VMware, Inc.
info:  GL renderer:     Gallium 0.4 on llvmpipe (LLVM 3.6, 256 bits)
info:  GL version:      3.0 Mesa 10.5.3
info:  GL hw accelerated:       no
Running 64-bit tests
info:  libGL.so.1:      loaded from: /usr/lib64/libGL.so.1
info:  libGL.so.1:      symlink to:  /usr/lib64/libGL.so.1.2.0
info:  X display:       :0
info:  X Ext. "GLX":    present
info:  X Ext. "NV-GLX": not present; OK for non-nVidia drivers
info:  GLX server:      SGI
info:  GLX client:      Mesa Project and SGI
info:  GL vendor:       Intel Open Source Technology Center
info:  GL renderer:     Mesa DRI Intel(R) Ivybridge Mobile 
info:  GL version:      3.0 Mesa 10.5.3
Checking secondary (usually NVIDIA) GL
Running 32-bit tests
info:  libGL.so.1:      loaded from: /usr/lib/nvidia-bumblebee/libGL.so.1
info:  libGL.so.1:      symlink to:  /usr/lib/nvidia-bumblebee/libGL.so.349.16
info:  X display:       :8
info:  X Ext. "GLX":    present
info:  X Ext. "NV-GLX": present
info:  GLX server:      NVIDIA Corporation
info:  GLX client:      NVIDIA Corporation
info:  GL vendor:       NVIDIA Corporation
info:  GL renderer:     GeForce GT 635M/PCIe/SSE2
info:  GL version:      4.5.0 NVIDIA 349.16
Running 64-bit tests
info:  libGL.so.1:      loaded from: /usr/lib64/nvidia-bumblebee/libGL.so.1
info:  libGL.so.1:      symlink to:  /usr/lib64/nvidia-bumblebee/libGL.so.349.16
info:  X display:       :8
info:  X Ext. "GLX":    present
info:  X Ext. "NV-GLX": present
info:  GLX server:      NVIDIA Corporation
info:  GLX client:      NVIDIA Corporation
info:  GL vendor:       NVIDIA Corporation
info:  GL renderer:     GeForce GT 635M/PCIe/SSE2
info:  GL version:      4.5.0 NVIDIA 349.16
Testing offloading with primus
Running 32-bit tests
info:  libGL.so.1:      loaded from: /usr/lib/primus/libGL.so.1
info:  X display:       :0
info:  X Ext. "GLX":    present
info:  X Ext. "NV-GLX": not present; OK for non-nVidia drivers
info:  GLX server:      NVIDIA Corporation
info:  GLX client:      primus
libGL error: unable to load driver: i965_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: i965
info:  GL vendor:       NVIDIA Corporation
info:  GL renderer:     GeForce GT 635M/PCIe/SSE2
info:  GL version:      4.5.0 NVIDIA 349.16
Running 64-bit tests
info:  libGL.so.1:      loaded from: /usr/lib64/primus/libGL.so.1
info:  X display:       :0
info:  X Ext. "GLX":    present
info:  X Ext. "NV-GLX": not present; OK for non-nVidia drivers
info:  GLX server:      NVIDIA Corporation
info:  GLX client:      primus
info:  GL vendor:       NVIDIA Corporation
info:  GL renderer:     GeForce GT 635M/PCIe/SSE2
info:  GL version:      4.5.0 NVIDIA 349.16

**Comment by amonakov** [comment]
As you can see, 32-bit i965_dri.so is missing.

_Edited to add:_ or perhaps not missing, but incompatible, e.g. a different version than Mesa expects.

**Comment by WhiteWolf1776** [comment]
Thanks, I'll dig that direction.  As that i965 error showed up even without primusrun, but the app still ran, I assumed it was just noise. (me and my assumptions ;) )

Thanks again.

**Comment by ryanpcmcquen** [comment]
Thanks for this. I am going to try a downgrade to Mesa 10.4.7. Wish me luck! :penguin:

**Comment by WhiteWolf1776** [comment]
Turned out to be a mesa build issue.  the x86 needed to be built with i586 flags now as i486 just doesn't work.

Slackware-current is now working again as expected, just putting that there in case anyone else gets hit with it.

Thanks for the help :)
