### ISSUE TITLE
Unvanquished segfaults after "primus: fatal: failed to acquire direct rendering context"

### ISSUE THREAD

**Issue by mjstahlberg** [amonakov/primus#168]
The game Unvanquished version 0.38.0 on x86_64 crashes after `primus: fatal: failed to acquire direct rendering context for display thread` and other OpenGL related warnings. The full program log can be found [here](http://hastebin.com/unuqeqelof.vbs). Using `optirun`, the game could be launched. The game version in question can be downloaded via [torrent](https://cdn.unvanquished.net/unvanquished_0.38.0.torrent) or [web](https://sourceforge.net/projects/unvanquished/files/Universal_Zip/unvanquished_0.38.0.zip/download).

Please refer to the original issue on the Unvanquished tracker for more details: Unvanquished/Unvanquished#712.

**Comment by Letiliel** [comment]
This was using primus from the Stable Bumblebee PPA.
 I tried compiling from source but got into errors and abandoned, sorry.

**Comment by amonakov** [comment]
Please add output of `glsanity-bee` (https://github.com/amonakov/glsanity) from an affected system.

Also please run the game with `primusrun env LIBGL_DEBUG=verbose LD_DEBUG=libs LD_DEBUG_OUTPUT=/tmp/unv-ld.txt` and supply console output and `/tmp/unv-ld.txt` files.

**Comment by Letiliel** [comment]
[glsanity-bbee's output](http://hastebin.com/gopovojewu.sm)
[Output with env](http://hastebin.com/jebepowace.vbs)
unv-ld.txt file [1](http://hastebin.com/ziqoficizo.js), [2](http://hastebin.com/xodatimuta.avrasm), [3](http://hastebin.com/uwanumuniq.avrasm)

**Comment by amonakov** [comment]
Thanks. The issue is: the distribution of Unvanquished is including an incompatible version of libglapi.so.

**Comment by Letiliel** [comment]
Alright. I guess it's up to the Unvanquished team to fix this if they want to.
