### ISSUE TITLE
Primusrun crash, related to DRI2?

### ISSUE THREAD

**Issue by KarenRei** [amonakov/primus#173]
I've been working with @gsgatlin on this issue and they said I should start a thread for you as well. You can see the details of the problem(s) over in this thread:

https://github.com/Bumblebee-Project/Bumblebee/issues/671

The main symptoms are a crash in primusrun and the inability to output on HDMI. Hopefully you have some useful input  :)

**Comment by amonakov** [comment]
I see that you've already resolved the issues. The main cause was the "nomodeset" kernel command line flag.

You don't need intel-virtual-output since all video outputs are on your Intel GPU (what matters for you is that HDMI output is on Intel chip, not nVidia).
