### ISSUE TITLE
primus silently does nothing or produces segmentation fault

### ISSUE THREAD

**Issue by neildarlow** [amonakov/primus#175]
Environment:
Fedora 22 Workstation running GNOME on Toshiba Satellite (i5 Quad core/8GB Ram/Secure boot disabled).
Linux satellite 4.1.3-200.fc22.x86_64 #1 SMP Wed Jul 22 19:51:58 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
kernel-4.1.3-200.fc22.x86_64
kernel-core-4.1.3-200.fc22.x86_64
kernel-devel-4.1.3-200.fc22.x86_64
kernel-headers-4.1.3-200.fc22.x86_64
kernel-modules-4.1.3-200.fc22.x86_64

Video graphics:
00:02.0 VGA compatible controller: Intel Corporation Broadwell-U Integrated Graphics (rev 09)
09:00.0 3D controller: NVIDIA Corporation GM108M [GeForce 930M](rev ff)

Bumblebee RPM versions:
bbswitch-0.8.0-1.fc22.x86_64
bumblebee-3.2.1-7.fc22.x86_64
bumblebee-nonfree-release-1.2-1.noarch
bumblebee-nvidia-352.21-1.fc22.x86_64
bumblebee-release-1.2-1.noarch
primus-1.1.03282015-2.fc22.x86_64

Problem description:
The bbswitch module is loaded and modinfo bbswitch returns valid output.
optirun works fine and nvidia graphics are used.
optirun -b primus and primusrun result in one of two conditions:
1) The specified command does not execute and no error is reported.
2) The specified command does not execute and a segmentation fault with core dump results.

Additional information:
As far as I can determine, my Fedora 22 installation is pure 64-bit i.e. there are no .i686 RPMs installed and I have not installed any 32-bit bumblebee packages. Is this relevant to what I am seeing?

I am new to bumblebee but will happily provide any required information or undertake and investigations you suggest.

Regards,
Neil Darlow

**Comment by gsgatlin** [comment]
Hello,

Can you try running

primusrun glxgears -info

and after it crashes/does nothing, can you paste the following logs to a site such as

http://pastebin.com/      or  http://fpaste.org/      log files are:

/var/log/messages

and also

/var/log/Xorg.8.log

Also, does virtualgl work with bumblebee? (optirun -b virtualgl glxgears -info)

**Comment by neildarlow** [comment]
Hi,

VirtualGL works fine with bumblebee.

My Xorg.8.log after primusrun is at http://paste.fedoraproject.org/250244

It appears that Fedora 22 workstation uses the systemd journal for logging. There is no /var/log/messages file. Can you work with any excerpt of that, otherwise I will have to install and configure rsyslog.

Regards,
Neil Darlow

**Comment by gsgatlin** [comment]
Thats ok. I think I found your problem in the X log...

You have "nomodeset" as a kernel option. Which will break primus.

So can you remove that?

Like you can edit:

/etc/default/grub

and then either

/boot/grub2/grub.cfg

or

/boot/efi/EFI/fedora/grub.cfg

whichever one you have. Does that help?

I guess maybe the installer is adding that on some people's systems for some reason.

**Comment by neildarlow** [comment]
Hi,

Right on the button! Works perfectly now. Thank you.

It's actually a case of doing the following:
1) Remove nomodeset from command line in /etc/default/grub
2) As root execute grub2-mkconfig -o /boot/efi/EFI/fedora/grub.cfg
3) Reboot

Regards,
Neil Darlow
