### ISSUE TITLE
Problem with steam - arch linux

### ISSUE THREAD

**Issue by Kezii** [amonakov/primus#180]
I'm having problems with steam and primusrun, it won't start any steam game, no matter which game / game engine, here's the console output:

```
Game update: AppID 4000 "Garry's Mod", ProcID 23240, IP 0.0.0.0:0
ERROR: ld.so: object '/home/kezio/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/kezio/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/kezio/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/kezio/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
/bin/bash: /home/kezio/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /usr/lib/primus/libGL.so.1)
Game removed: AppID 4000 "Garry's Mod", ProcID 23240
```

I think the second last line is the relevant one, can anyone give me some pointers?
Thanks

**Comment by karolherbst** [comment]
you need a 32bit version for 32 bit games

**Comment by karolherbst** [comment]
ohh wait, I think you need a newer libstdc++ library installed than you currently have, maybe by installing a newer gcc version or something?

"libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /usr/lib/primus/libGL.so.1)"

**Comment by karolherbst** [comment]
I think you need at least a gcc-5 runtime installed

**Comment by akien-mga** [comment]
Well that's likely the contrary, you have a too new glibc version for the Steam runtime. The primus version that you built (or the package you're using) was built using GLIBCXX_3.4.21, and it's not compatible with Steam's libstdc++.so.6.

You could try to remove the C++ libraries from the steam runtime to see how it goes.

**Comment by karolherbst** [comment]
ohh right, this issue agian, yes @akien-mga is right

**Comment by Kezii** [comment]
I removed that file and now it works, thanks a lot
