### ISSUE TITLE
Error building primus with clang

### ISSUE THREAD

**Issue by slacka** [amonakov/primus#189]
Trying to build primus with clang results in:
`./gl-passthru.def:2:1: error: unknown attribute 'ifunc' ignored [-Werror,-Wunknown-attributes]`

The full log of this error can be found here:
http://clang.debian.net/logs/2016-08-30/primus_0~20150328-4_unstable_clang.log

**Comment by amonakov** [comment]
It appears that Clang supports the ifunc attribute only starting from version 3.9, and your log indicates that 3.8 was used.

Apologies for relying on this unportable feature, but alternative approaches have drawbacks too.
