### ISSUE TITLE
Tag a release?

### ISSUE THREAD

**Issue by zx2c4** [amonakov/primus#190]
Primus has seen no commits and seems fairly stable since a while. Could you tag a release?

**Comment by karolherbst** [comment]
does it matter?

**Comment by melroy89** [comment]
It makes it more clear at least.

See also issue: #169

**Comment by zx2c4** [comment]
Yes, it makes a huge difference for downstream distribution packagers. Please make a release.

**Comment by zx2c4** [comment]
0.2 was tagged.
