### ISSUE TITLE
your contact in Gentoo

### ISSUE THREAD

**Issue by jonasstein** [amonakov/primus#198]
Hi, 
you are listed in Gentoo as "Proxied Maintainer" who will fix Gentoo bugs of this package, is that correct?
https://packages.gentoo.org/packages/x11-misc/primus
https://bugs.gentoo.org/633310

**Comment by amonakov** [comment]
I've never been an active Gentoo contributor, so I'm a bit surprised at that; I don't think I would give higher priority to Gentoo bugs. That said, is the issue just about email addresses registered at Gentoo BZ? I do have an account there, but the address is amonakov+bugs.gentoo@gmail.com

**Comment by jonasstein** [comment]
Thank you so much for your quick reply. Then someone added you by mistake. I will remove you from this package today.
